apiVersion: apps/v1
kind: Deployment
metadata:
  name: app  # Used for kustomize matching
spec:
  replicas: 2  # let's do 2 instances in dev
  template:
    spec:
      containers:
        - name: app # Used for kustomize matching
          imagePullPolicy: Always # in order to always download :latest or :SNAPSHOT images
