commonLabels:
  variant: dev
commonAnnotations:
  note: Hello, I am dev!
images:
  - name: docker.io/spring/testapp  #used for Kustomize matching
    newName: docker.io/markpollack/testing
    newTag: 8f0df65d4ceeb1cd189d2ff1ec2797267d89442b
resources:
  - ../base
  - deployment.yaml

